name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar unzip
        run: sudo apt-get install unzip -y

      - name: Descomprimir proyecto
        run: unzip femontv.zip -d project

      - name: Buscar gradlew
        id: find_gradle
        run: |
          GRADLE_PATH=$(find project -name gradlew | head -n 1)
          echo "GRADLE_PATH=$GRADLE_PATH" >> $GITHUB_ENV

      - name: Dar permisos
        run: chmod +x $GRADLE_PATH

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar APK
        run: |
          cd $(dirname $GRADLE_PATH)
          ./gradlew assembleDebug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: project/**/build/outputs/apk/debug/*.apk      
